project:
  type: website
website:
  title: GoldRMy1
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        href: lectures.qmd
      - text: "Labs"
        href: labs.qmd
      - text: "DataSkills"
        href: dataskills.qmd
      - text: "R Resources"
        href: r-resources.qmd


  sidebar: 
    style: "docked"
    search: true
    collapse-level: 0
    contents: 
      - section: "Week 01"
        contents:
          - href: worksheets/worksheet01/lab.qmd
            text: Lab Worksheet Week 01
          - href: week01/01-ttests.qmd
            text: Week 01 Reading
          - href: week01/lab.qmd
            text: Week 01 Lab
          - href: week01/dataskills.qmd
            text: Week 01 DataSkills
      - text: "---"
      - section: "Demonstrations"
        contents:
          - auto: "demos/*-demo.qmd"

format:
  html:
    theme:
    - cosmo
    - brand
    css:
    - styles.css
    - include/webex.css
    code-link: true
    mainfont: Atkinson Hyperlegible
    monofont: Source Code Pro
    grid:
      sidebar-width: 250px
      margin-width: 150px
    toc: true
    toc-depth: 2
    include-after-body: include/webex.js
    embed-resources: true
