project:
  type: website
website:
  title: GoldRMy1
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: webr.qmd
      text: Webr Demo
    - href: webexercises.qmd
      text: Webexercises Demo
    - href: iframeslides.qmd
      text: Embedded Slides

  sidebar: 
    contents: 
    - href: lab.qmd
      text: Lab Worksheet example

format:
  html:
    theme:
    - cosmo
    - brand
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
